#!/bin/bash

echo "********RUNNING PROJECT 2********"

echo "make main"
make main

./main a1.in
cat a1.out

echo "********running a2.in********"
./main a2.in
cat a2.out

echo "********running a3.in********"
./main a3.in
cat a3.out

echo "********running a4.in********"
./main a4.in
cat a4.out

echo "********running a5.in********"
./main a5.in
cat a5.out

echo "********running a6.in********"
./main a6.in
cat a6.out

echo "********running a7.in********"
./main a7.in
cat a7.out

echo "********running a8.in********"
./main a8.in
cat a8.out

echo "********END OF PROJECT 2********"
echo "make clean"
make clean
